### ISSUE TITLE
How to use custom mapping when indexing data

### ISSUE THREAD

**Issue by eyeezzi** [firebase/flashlight#102]
I have a firebase node like so

```
$game
   |--location
   |     |
   |     |--lat: 40
   |     |
   |     |__lon: 50
   |
   |__others
```
I would like to index this node in Elastic search and be able to perform geolocation queries using the `location` field. The ES documentation states that the location field must be manually mapped as a _**geo_point**_ when the document is indexed, how can I do this using Flashlight? For now, Flashlight simply indexes the document with default ES dynamic mapping as follows:

```
{
  "firebase": {
        "mappings": {
            "game": {
                "properties": {
                    "location": {
                        "properties": {
                            "lat": {
                                "type": "long"
                            },
                            "lon": {
                                "type": "long"
                            }
                        }
                    },
                    "others" {
                        ...
                    }
                }
            }
        }
    }
}
```

**Comment by katowulf** [comment]
You'd need to use the `parser` attribute to coax the data into a format suitable for your code. If you can't make that work, it's outside the scope of Flashlight, and you'll have to adapt it to your needs.
