### ISSUE TITLE
Dyamic paths are not working.

### ISSUE THREAD

**Issue by kleeb** [firebase/flashlight#110]
Am I missing something, or setting dynamic path is not possible in flashlight?

Lets say I have this kind of path:

products/$productID/features/$featureId

where products keep the list of products and features is a list of features in this product, so that I want to search by some features of all products in the list.

is it possible to setup a path on the list of features of all products (and in result receive both ids)?

**Comment by katowulf** [comment]
What have you tried that isn't working? It's unclear what you're expecting here.

**Comment by kleeb** [comment]
I used path ``products/$productID/features/100`` and received no results

**Comment by katowulf** [comment]
You can't use `$` in Firebase keys, so that's not a valid path.
