### ISSUE TITLE
'search/response' not getting populated 

### ISSUE THREAD

**Issue by zacck** [firebase/flashlight#117]
Hello! I am sorry if I am posting this on the wrong forum.
This is what I have attempted.
I have set up  flashlight in my application that is hosted on heroku my config.js looks like 
https://gist.github.com/zacck/dfdb9022d97d18e25b7bbc3754cd57eb

and I am connecting to the elastic search cluster like this in my entry point 
https://gist.github.com/zacck/5aa1c9be51a59f37bd0df3608a3f3502

... 
Here I face my first issue when working by way of the BONSAI_URL 
I get a http link and my browser wont let the request to my bonsai_url go  through until I allow unsafe scripts. This is what the console log looks like.

https://gist.github.com/zacck/e09cb97491dfea8c004e957e9c4a22d4

When i do allow loading of unsafe scripts 2 things happen the firebase path 
"search/request"
is written to with an object that looks like 
```
search 
 request
 -K_DXW1uATM6BnXmYUaG
 index: 
"firebase"
 q: 
"Kaya"
 type: 
"supplier"
```

But it never writes to the

"search/reponse"

is it possible to get advice on what I could be doing wrong?

My search query looks like this 
```
//build a query
    var query = {
      index: 'firebase',
      type: 'supplier'
    }
    // add term
    query.q = term;

    //do the search
    var searchRef = firebaseRef.child('search');
    var key = searchRef.child('request').push(query).key;
    console.log('search', key, query);

    //read results
    searchRef.child('response/'+key).on('value', (snap) => {
      var dat = snap.val();
      if( dat === null ) { return; } // wait until we get data
      console.log(dat);
    });`
```

Upon further reading i realize my app never logs the  indexing part of the set up 
i.e 

`Indexing firebase/path using path "Posts"
Queue started, IN: "search/request", OUT: "search/response"`

I assume my issues begin here

**Comment by katowulf** [comment]
Please provide your security rules, sample data from the query in search/request, version info.

Most likely, the Flashlight service isn't answering requests or is crashing on deploy. Does it work if you run it locally rather than remotely on Heroku? That's the first item to verify.

After that, you'll want to share your deploy logs and the remote server logs for the Flashlight service on Heroku. You'll likely find a permission denied or an issue talking to ES in those.

**Comment by zacck** [comment]
This is how my security rules look like 
```
{
   "rules": {
     ".read": true,
     ".write": true,
     "search": {
         "request": {
            "$recid": {
               // I can only read records assigned to me
               ".read": true,
               // I can only write new records that don't exist yet
               ".write": "!data.exists() && (newData.child('id').val() === auth.id || newData.child('id').val() === auth.uid)",
               ".validate": "newData.hasChildren(['index', 'type']) && (newData.hasChild('q') || newData.hasChild('query') || newData.hasChild('body'))",
               "index": {
                  // accepts arrays or strings
                  ".validate": "(newData.isString() && newData.val().length < 1000) || newData.hasChildren()",
                  "$child": {
                     ".validate": "newData.isString() && newData.val().length < 1000"
                  }
               },
               "type": {
                  // accepts arrays or strings
                  ".validate": "(newData.isString() && newData.val().length < 1000) || newData.hasChildren()",
                  "$child": {
                     ".validate": "newData.isString() && newData.val().length < 1000"
                  }
               },
               "query": {
                  // lucene formatted string, such as "title:search_term" or a `body` attribute
                  // see https://www.elastic.co/guide/en/elasticsearch/guide/current/query-dsl-intro.html
                  ".validate": "newData.isString() || newData.hasChildren()"
               },
               "body": {
                  // The `body` object of an ES search, such as { size: 25, from: 0, query: "*foo*" }, see
                  // https://www.elastic.co/guide/en/elasticsearch/guide/current/query-dsl-intro.html
                  ".validate": "newData.hasChildren()"
               },
               "q": {
                  // lucene formatted 'lite' search string, such as "*foo*" or "+name:(mary john) +date:>2014-09-10", see
                  // https://www.elastic.co/guide/en/elasticsearch/guide/current/search-lite.html
                  ".validate": "newData.isString()"
               },
               "size": {
                  ".validate": "newData.isNumber() && newData.val() >= 0"
               },
               "from": {
                 ".validate": "newData.isNumber() && newData.val() >= 0"
               },
               "$other": {
                  ".validate": false
               }
            }
         },
         "response": {
           ".indexOn": "timestamp",
            "$recid": {
              // I can only read/write records assigned to me
              ".read": true,
              // delete only
              ".write": true
            }
         }
      }
   }
}


```


As for my version information 

 I am using
node 6.2.0 
firebase 3.0.2 
elasticsearch 11.0.1
JQDeferred 1.9.1


my data in the search/request object looks this way 

```
{
  "request" : {
    "-K_DXW1uATM6BnXmYUaG" : {
      "index" : "firebase",
      "q" : "Kaya",
      "type" : "supplier"
    },
    "-K_DXZJLEyYkNS-hKhU2" : {
      "index" : "firebase",
      "q" : "Kaya",
      "type" : "supplier"
    },
    "-K_D_sPllJrDPc1Fugz3" : {
      "index" : "firebase",
      "q" : "Kaya",
      "type" : "supplier"
    }
  }
}


```

Currently I just have the app trying to push a query everytime it loads and trying to log any responses from the search/response information

Please let me know if there is any more information I can provide I am currently enabling logging and will report the results of that back

**Comment by zacck** [comment]
Thank you so much for the time you are taking to walk me through this I truly appreciate this.

**Comment by zacck** [comment]
When i run elasticsearch locally it seems to connect to firebase and elasticsearch 
what I dont see is that it never actually indexes the data here is the log from running the app locally with a local elastic search 

```
[90mConnecting to ElasticSearch host localhost:9200[39m
(unknown) 0: set {"path":"/search/request/-K_IdxPWcKiWOXu4pHbZ","value":{"index":"firebase","type":"supplier","q":"Kaya"},"ug":null}  
(unknown) p:0: Buffering put: /search/request/-K_IdxPWcKiWOXu4pHbZ  
(unknown) search -K_IdxPWcKiWOXu4pHbZ Object
(unknown) p:0: Listen called for /search/response/-K_IdxPWcKiWOXu4pHbZ default  
(unknown) p:0: Auth token refreshed  
(unknown) p:0: Making a connection attempt  
(unknown) getToken() completed. Creating connection. 
(unknown) c:0:0: Connection created  
(unknown) c:0:0:0 Websocket connecting to wss://jets-backennd.firebaseio.com/.ws?v=5  
(unknown) [WDS] Warnings while compiling.
(unknown) ./~/colors/colors.js
219:30 Critical dependency: the request of a dependency is an expression
CriticalDependencyWarning: Critical dependency: the request of a dependency is an expression
    at CommonJsRequireContextDependency.getWarnings (/Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/dependencies/CommonJsRequireContextDependency.js:22:4)
    at /Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/Compilation.js:645:21
    at Array.forEach (native)
    at /Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/Compilation.js:644:22
    at Array.forEach (native)
    at Compilation.reportDependencyWarnings (/Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/Compilation.js:643:9)
    at Compilation.<anonymous> (/Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/Compilation.js:505:8)
    at Array.forEach (native)
    at Compilation.finish (/Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/Compilation.js:504:15)
    at Compiler.<anonymous> (/Users/zacck/Documents/www/backend_cms/node_modules/webpack/lib/Compiler.js:466:16)
warnings
database.js?c1ba:53 c:0:0:0 Websocket connected.  
database.js?c1ba:53 c:0:0: Realtime connection established.  
database.js?c1ba:53 p:0: connection ready  
database.js?c1ba:53 p:0: reportStats {"c":{"sdk.js.3-6-3":1}}  
database.js?c1ba:53 p:0: {"r":1,"a":"s","b":{"c":{"sdk.js.3-6-3":1}}}  
database.js?c1ba:53 p:0: Listen on /search/response/-K_IdxPWcKiWOXu4pHbZ for default  
database.js?c1ba:53 p:0: {"r":2,"a":"q","b":{"p":"/search/response/-K_IdxPWcKiWOXu4pHbZ","h":""}}  
database.js?c1ba:53 p:0: {"r":3,"a":"p","b":{"p":"/search/request/-K_IdxPWcKiWOXu4pHbZ","d":{"index":"firebase","q":"Kaya","type":"supplier"}}}  
database.js?c1ba:53 p:0: from server: {"r":1,"b":{"s":"ok","d":""}}  
database.js?c1ba:53 c:0:0: Primary connection is healthy.  
database.js?c1ba:53 p:0: from server: {"r":2,"b":{"s":"ok","d":{}}}  
database.js?c1ba:53 p:0: listen response {"s":"ok","d":{}}  
database.js?c1ba:53 event: /search/response/-K_IdxPWcKiWOXu4pHbZ:value:null 
database.js?c1ba:53 p:0: from server: {"r":3,"b":{"s":"ok","d":""}}  
database.js?c1ba:53 p:0: p response {"s":"ok","d":""}  
:8080/#/?_k=c212tr:1 XMLHttpRequest cannot load http://localhost:9200/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
console.js?dd2c:38 ERROR: 2016-12-31T06:53:50Z
  Error: Request error, retrying
  HEAD http://localhost:9200/ => Request failed to complete.
      at Log.error (eval at <anonymous> (http://localhost:8080/assets/app.bundle.js:943:1), <anonymous>:225:56)
      at checkRespForFailure (eval at <anonymous> (http://localhost:8080/assets/app.bundle.js:1059:1), <anonymous>:240:18)
      at XMLHttpRequest.xhr.onreadystatechange (eval at <anonymous> (http://localhost:8080/assets/app.bundle.js:2874:1), <anonymous>:78:7)


Console.write @ console.js?dd2c:38
(anonymous) @ console.js?dd2c:52
wrapper @ index.js?3d0b:3232
EventEmitter.emit @ events.js?d5a0:81
Log.error @ log.js?d20a:225
checkRespForFailure @ transport.js?c66d:240
xhr.onreadystatechange @ xhr.js?4e7e:78
:8080/#/?_k=c212tr:1 XMLHttpRequest cannot load http://localhost:9200/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access.
console.js?dd2c:38 WARNING: 2016-12-31T06:53:50Z
```

**Comment by zacck** [comment]
Odd Discovery.
When I run the flashlight clone with my configuration ... on my local development server The application on heroku actually manages to search and find results. 
The one glaring difference is when I run the flashlight application I can see the indexing happening 

```
Isaacs-MacBook-Pro:flashlight zacck$ node app.js 
Connecting to ElasticSearch host localhost:9200
Connected to ElasticSearch host localhost:9200
Connecting to Firebase https://xxxx.firebaseio.com
The 'serviceAccount' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.
Indexing firebase/supplier from DB "suppliers"
Queue started, IN: "search/request", OUT: "search/response"
Next cleanup in 60 seconds
processing query request -K_QdB4zk_xtSyFljV0g
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
processing query request -K_QdNFkgDeMzo0qZbDj
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
processing query request -K_QdSXt_-czcjTqrQq4
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
processing query request -K_QdaSZE0ttdO65VWUO
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
query result -K_QdB4zk_xtSyFljV0g: 2 hits
query result -K_QdaSZE0ttdO65VWUO: 2 hits
indexed firebase/supplier/-KSqJVYhmp-uKTRB6t0L
query result -K_QdSXt_-czcjTqrQq4: 2 hits
query result -K_QdNFkgDeMzo0qZbDj: 2 hits
indexed firebase/supplier/-KSvN9P_E0wAIpY6mUSH
indexed firebase/supplier/-KSpxoS9DYkmj1NsM_iQ
indexed firebase/supplier/-KSuwxgfwBPj-K7uFbcx
indexed firebase/supplier/-KSv1UatDVk-f6bO4V_x
indexed firebase/supplier/-KTrgeRzmwKoLnnU3AxR
housekeeping: found 4 outbound orphans (removing them now) Sun Jan 01 2017 22:10:07 GMT+0200 (SAST)
Next cleanup in 60 seconds
Next cleanup in 60 seconds
processing query request -K_Qe59AqrXo4YLDoRL-
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
query result -K_Qe59AqrXo4YLDoRL-: 2 hits
housekeeping: found 1 outbound orphans (removing them now) Sun Jan 01 2017 22:12:08 GMT+0200 (SAST)
Next cleanup in 60 seconds
Next cleanup in 60 seconds
Next cleanup in 60 seconds
Next cleanup in 60 seconds

```

However when I run my application it stops at the connecting to firebase part

Below is what happens when I run the application and flashlight isnt running 

```
Configured using BONSAI_URL environment variable https://xxxxxx-1525933.us-east-1.bonsaisearch.net Object {FB_URL: "https://xxx.firebaseio.com", FB_REQ: "search/request", FB_RES: "search/response", FB_SERVICEACCOUNT: "service-account.json", ES_HOST: "ash-1525933.us-east-1.bonsaisearch.net"…}
app.bundle.js:128 [90mConnecting to ElasticSearch host xxx-1525933.us-east-1.bonsaisearch.net:80[39m
app.bundle.js:3 search -K_QfUFG59AE5jLuEg4I Object {index: "firebase", type: "supplier", q: "Kaya"}
app.bundle.js:43 Mixed Content: The page at 'https://backendjtx.herokuapp.com/#/?_k=dzm91x' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ash-1525933.us-east-1.bonsaisearch.net/'. This content should also be served over HTTPS.
r.request @ app.bundle.js:43
r @ app.bundle.js:8
l.applyArgs @ app.bundle.js:2
p @ app.bundle.js:24
l.run @ app.bundle.js:3
s @ app.bundle.js:3
/#/?_k=dzm91x:1 Mixed Content: The page at 'https://backendjtx.herokuapp.com/#/?_k=dzm91x' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ash-1525933.us-east-1.bonsaisearch.net/'. This content should also be served over HTTPS.
app.bundle.js:128 [90mConnected to ElasticSearch host ash-1525933.us-east-1.bonsaisearch.net:80[39m
app.bundle.js:128 [90mConnecting to Firebase https://jets-backennd.firebaseio.com[39m

```

and here you can see what happens when I run the application and flashlight is running 

from app on heroku 

``` 
Configured using BONSAI_URL environment variable https://qc7shwwr:phgltodb5vbqqpxl@ash-1525933.us-east-1.bonsaisearch.net Object {FB_URL: "https://jets-backennd.firebaseio.com", FB_REQ: "search/request", FB_RES: "search/response", FB_SERVICEACCOUNT: "service-account.json", ES_HOST: "ash-1525933.us-east-1.bonsaisearch.net"…}
app.bundle.js:128 [90mConnecting to ElasticSearch host ash-1525933.us-east-1.bonsaisearch.net:80[39m
app.bundle.js:3 search -K_QgEJCkT1Wf8PBhI-i Object {index: "firebase", type: "supplier", q: "Kaya"}
app.bundle.js:3 found 2 items Object {hits: Array[2], max_score: 0.8462581, total: 2}
app.bundle.js:43 Mixed Content: The page at 'https://backendjtx.herokuapp.com/#/?_k=dzm91x' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ash-1525933.us-east-1.bonsaisearch.net/'. This content should also be served over HTTPS.
r.request @ app.bundle.js:43
r @ app.bundle.js:8
l.applyArgs @ app.bundle.js:2
p @ app.bundle.js:24
l.run @ app.bundle.js:3
s @ app.bundle.js:3
app.bundle.js:128 [90mConnected to ElasticSearch host ash-1525933.us-east-1.bonsaisearch.net:80[39m
app.bundle.js:128 [90mConnecting to Firebase https://jets-backennd.firebaseio.com[39m

``` 

from running the flashlight sample on my local server 

```
Isaacs-MacBook-Pro:flashlight zacck$ node app.js 
Connecting to ElasticSearch host localhost:9200
Connected to ElasticSearch host localhost:9200
Connecting to Firebase https://jets-backennd.firebaseio.com
The 'serviceAccount' property specified in the first argument to initializeApp() is deprecated and will be removed in the next major version. You should instead use the 'firebase-admin' package. See https://firebase.google.com/docs/admin/setup for details on how to get started.
Indexing firebase/supplier from DB "suppliers"
Queue started, IN: "search/request", OUT: "search/response"
Next cleanup in 60 seconds
processing query request -K_QfPS7PnbKGeI_1YN3
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
processing query request -K_QfUFG59AE5jLuEg4I
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
indexed firebase/supplier/-KSpxoS9DYkmj1NsM_iQ
indexed firebase/supplier/-KSv1UatDVk-f6bO4V_x
indexed firebase/supplier/-KSqJVYhmp-uKTRB6t0L
indexed firebase/supplier/-KSvN9P_E0wAIpY6mUSH
indexed firebase/supplier/-KSuwxgfwBPj-K7uFbcx
query result -K_QfUFG59AE5jLuEg4I: 2 hits
query result -K_QfPS7PnbKGeI_1YN3: 2 hits
indexed firebase/supplier/-KTrgeRzmwKoLnnU3AxR
processing query request -K_QgEJCkT1Wf8PBhI-i
built query { index: 'firebase', q: 'Kaya', type: 'supplier' }
query result -K_QgEJCkT1Wf8PBhI-i: 2 hits
housekeeping: found 3 outbound orphans (removing them now) Sun Jan 01 2017 22:21:32 GMT+0200 (SAST)
Next cleanup in 60 seconds

``` 

As you can see the local ES server gets called when I run the app on heroku and it gets results

**Comment by katowulf** [comment]
It's not really clear what is what in your post here. If you run a local server and it's answering the requests, it makes sense that they work. The Heroku server is probably not doing anything at all here. Keep in mind that Flashlight manages all the interactions via the realtime database.

Note that your local service is connecting to a LOCAL INSTANCE OF ElasticSearch, so this doesn't even accurately test that your remote ElasticSearch instance is even running. Where did you deploy this? Try testing your local instance by connecting to the ES instance your Heroku service is attempting.

If it's working locally and not on Heroku, then the Heroku worker is not being installed correctly, not able to reach ElasticSearch (probably due to Firewall/security restrictions), or not able to talk to Firebase (probably because you haven't uploaded your service account info or such). There are probably other options here, too.

Without a minimal working repro, I can't be any more help here. See [how to ask](http://stackoverflow.com/help/how-to-ask) and [creating an mcve](http://stackoverflow.com/help/mcve).

**Comment by zacck** [comment]
Deverloper was the issue in this case.

**Comment by fahadjabbar8** [comment]
Please Make sure that your security rules on fire base portal are in valid Json !

**Comment by zacck** [comment]
@fahadjabbar8  issue was closed last year?
