### ISSUE TITLE
What is FB_NAME and FB_TOKEN?

### ISSUE THREAD

**Issue by vinhhap** [firebase/flashlight#119]
Hello, while everything work fine in the local environment, I'm just wondering what is FB_NAME and FB_TOKEN when delpoy to Heroku because I have tried Project ID, Web API Key, Database Secrets and none of these works and all result in:
`{"error":"Authorization is required to perform this request. Please provide credentials, or contact support@bonsai.io for assistance.","status":401}`
when I run: 
`curl -X POST <BONSAI_URL>/firebase`
Thanks in advance!

**Comment by maitham1** [comment]
Hey, 

Try the [following](http://stackoverflow.com/questions/38276209/setting-up-flashlight-on-heroku-for-elasticsearch-with-new-firebase)

If not can you post a snippet of your config.js?

**Comment by katowulf** [comment]
Also, keep in mind that nothing you configure in config.js is going to affect your curl command. You'll need to add the auth creds to that manually, of course.
