### ISSUE TITLE
Using Flashlight with Angular 2

### ISSUE THREAD

**Issue by jadamconnor** [firebase/flashlight#123]
Are there any examples out there of Flashlight implementation in an Angular 2 app?

**Comment by katowulf** [comment]
None. But you just write to the search path and get data back from Flashlight, same as any other js client. Should be cake.

**Comment by jadamconnor** [comment]
Looking over exmaple.js I don't see where ElasticSearch comes in. I see we write to Firebase and show the snapshot values.

**Comment by katowulf** [comment]
Right. Flashlight also abstracts the requests to ES, which allows you to enforce Firebase security rules against search requests (e.g. require users to be authenticated). You write to Firebase and Flashlight makes the queries to ES on your behalf and writes the results back to Firebase. 

This is a queue strategy and a great way to USE Firebase as the central authority and security checkpoint, which reduces your server stack and complexity.

**Comment by jadamconnor** [comment]
One of the issues for me in translating to an Angular 2 implementation is that so many aspects of it are unfamiliar to me. For example, something I'm struggling with is the concept of how searches are indexed on an ES node in the first place. I see that we're writing search requests to Firebase. And you say that the requests to ES are being made as well. But as a user submits a search term, for example, said user is presumably searching for existing data. It seems like the query itself writes the data to search/requests and that the ES response is written to search/response(?). Is there an indexed version of your database already written on your ES cluster? Is that indexing something I'm to bake into my Firebase submissions? For example, when a new user is created in Firebase my code also indexes that user on an ES node?

**Comment by jadamconnor** [comment]
Thanks, kato. This clarifies a lot. So the paths we want monitor and index are objects in the `exports.paths` array in config.js? I think my lack of ES knowledge caused the comments in this section to be unclear to me.

**Comment by katowulf** [comment]
Yep, so from an AngularFire perspective, you only have to figure out how to write to search/request and read from search/result. Should be a simple service/module or extension of AngularFire functionality.

**Comment by jadamconnor** [comment]
A final question for you, if you don't mind--is it okay to serve Flashlight from the same Heroku app that Bonsai is on? I ask because only config.js is added to Heroku in the readme.  I assume it doesn't matter where I serve Flashlight from, but I want to be sure.

**Comment by katowulf** [comment]
Heroku, Google App Engine, AWS EC2 should all be fine.

**Comment by jadamconnor** [comment]
@katowulf, do you have any idea why all of my responses would be limited to 10 hits? As you can [see](https://i.gyazo.com/241c045f3c825de66adff94905d57270.png), the total is much higher than what I get back for hits.
