### ISSUE TITLE
App keeps crashing

### ISSUE THREAD

**Issue by jannikkeye** [firebase/flashlight#127]
Hi there,

I cannot get the app running on heroku. It seems to index the data fine but then crashes:

```
Web process failed to bind to $PORT within 60 seconds of launch
```

Any idea why it does that?

**Comment by katowulf** [comment]
You have started up a Heroku web dyno and this is not a web app (thus there is no process bound on port 80). You need to use a worker dyno instead.

**Comment by jannikkeye** [comment]
That makes sense, thanks for the quick reply. Great tool!
