### ISSUE TITLE
Connecting To Bonsai

### ISSUE THREAD

**Issue by kidequinox** [firebase/flashlight#132]
Hello,

I'm using Bonsai hosted elastic (not heroku) When I run the app.js. I'm getting an connection error.

`Elasticsearch ERROR: 2017-02-16T07:53:52Z                                                                                                                  
 Error: Request error, retrying
 Unable to revive connection: http://MY-URL.us-east-1.bonsaisearch.net:443/`

The sandbox bonsai URL is using HTTPS, but flashlight is using HTTP

**Comment by katowulf** [comment]
Use ES_HOST, ES_PORT, etc. instead of the BONSAI_URL.

**Comment by kidequinox** [comment]
I am, in the config file I have

 // ElasticSearch server's host URL
  exports.ES_HOST  = 'MY-BONSAI.us-east-1.bonsaisearch.net';

  // ElasticSearch server's host port
  exports.ES_PORT  = '443';

Still getting same error. It's attempting to use HTTP based on the output, but it should be using HTTPS

**Comment by katowulf** [comment]
Change ES_HOST to `https://my-bonsai....`?

**Comment by kidequinox** [comment]
When I do that it does:

`http://https://my-bonsai...`

**Comment by kidequinox** [comment]
any thoughts on how I can get around this ?
