### ISSUE TITLE
Get element by property value and without key

### ISSUE THREAD

**Issue by martinop** [firebase/flashlight#146]
If I have this object:
```
{
...
 amenities: {
 -KbvKvWicCNm_34rNJH9: {
     value: "Pool"
  },
 -K3dsadsicCNm_34rNJH9: {
     value: "Test"
  },
 -Kbv321312331234rNJH9: {
     value: "Tennis"
  },
}
...
}
```

How I can query elements with value "Tennis" without having the id/key of the parent object? ("-Kbv321312331234rNJH9")

**Comment by katowulf** [comment]
That's pretty much how ElasticSearch works. You index the amenities/ path in ES, then run your query on the data. The keys of the individual records are inconsequential.

See [example.js](https://github.com/firebase/flashlight/blob/master/example/example.js#L74). In that case, probably replace `_all` with `value`.

☼, Kato

**Comment by martinop** [comment]
Doesnt work

**Comment by katowulf** [comment]
What path are you indexing on relative to the amenities/ path? For prompt, quality answers, review [how to ask](http://stackoverflow.com/help/how-to-ask) and [creating an mcve](http://stackoverflow.com/help/mcve).
