### ISSUE TITLE
[question] How do you determine where to conduct the search? 

### ISSUE THREAD

**Issue by chrillewoodz** [firebase/flashlight#147]
I'm looking in the example files and I see that you choose a type which is what you'll be searching. What I can't wrap my head around though is that the value of type is either `user` or `message`, but the database paths seems to be `users` and `messages`. 

So how does flashlight know where to search?

**Comment by katowulf** [comment]
In `exports.paths`, we specify the `type` to index each record as in Flashlight. So the DB path it is taken from doesn't really play into the search portion.
