### ISSUE TITLE
[question] Questions regarding indexing

### ISSUE THREAD

**Issue by scottshipp** [firebase/flashlight#153]
When is data indexed by Flashlight? Is there a way to manually trigger a reindex? Is there a way to have it automatically reindex on a schedule?

Thank you!

**Comment by katowulf** [comment]
See [PathMonitor.js](https://github.com/firebase/flashlight/blob/master/lib/PathMonitor.js). It listens on paths configured in config.js for add/change/remove. To trigger a reindex, do one of those. No schedules needed.
