### ISSUE TITLE
Is it possible to let client index data?

### ISSUE THREAD

**Issue by tianhaoz95** [firebase/flashlight#155]
This is a great tool for firebase search. However, I kind of want to take it one step further. Is it possible to let client index the data? The mechanism is that whoever add a new data is responsible for indexing the data, and when I want to search, I just let client side code to do the search.

**Comment by katowulf** [comment]
To have the clients do the indexing, you'd need to open up ElasticSearch and make the requests there directly. It's [not particularly difficult to index data into ES](https://github.com/firebase/flashlight/blob/master/lib/PathMonitor.js#L43), pretty much a one line operation, but I'd ponder the security implications first as it sounds like the equivalent of having world read/write rules on your database (no way to secure ElasticSearch via rules like Firebase).
