### ISSUE TITLE
Running in production (not heroku or bonsai)

### ISSUE THREAD

**Issue by chrillewoodz** [firebase/flashlight#156]
I'm trying to get things up and running on a production server but I'm getting odd behaviour. I've uploaded the app and flashlight to the server, and added elasticsearch as a service.

However the server is requesting my local setup, so if I shut down the flashlight server locally I can't get any search results from elasticsearch.. Do I have to do anything in particular to make this work? 

I've got very little experience with servers etc so I think I haven't fully understood how to run things.

**Comment by chrillewoodz** [comment]
Turns out there was a permission rule at fault only.

**Comment by katowulf** [comment]
👍  thanks for circling back; glad you solved it : )
