### ISSUE TITLE
Query by bool with array of conditions

### ISSUE THREAD

**Issue by Rovalx** [firebase/flashlight#162]
Hi everyone. I'm struggling with making flashlight work by sending array of conditions to bool search. Here is my correct JSON body I am able to send with GET directly to elasticsearch:
`{
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*",
            "fields": [
              "username",
              "fullName"
            ]
          }
        },
        {
          "match": {
            "isPro": true
          }
        }
      ]
    }
  }
}`

Now, when I need to send it via Firebase to be handled by flashlight I'm getting error because this query is using "[", "]" when array is changed to paths and Flashlight/Firebase can't handle it. 

From the other hand when I'm not using array but object with nested objects separated by comma it dosen't work either - now elasticsearch is not able to handle JSON query.

**Comment by katowulf** [comment]
Try storing the `body` param as a string when you pass it to Flashlight. In other words, JSON.stringify() that before passing it in.

Also, try to be specific when reporting errors. "getting error" and "dosen't work either" are extremely broad and not helpful. See [how to ask](http://stackoverflow.com/help/how-to-ask) and [creating an mcve](http://stackoverflow.com/help/mcve).
