### ISSUE TITLE
Sort by inner object field.

### ISSUE THREAD

**Issue by umarhussain15** [firebase/flashlight#173]
I want to sort my result using the inner object field but firebase does not allow "innerObj.field" as key and throws error. 
Here is the structure of my data:
```
"products": {
    "$productId": {
     ...
     ...
      "vendor": {
        ...
        "name": "string"
      }
    }
  }
```
while sort for elastic search work like this: 
`"sort" :  { "field" : {"order" : "asc"}}`
doing `"sort" :  { "vendor.name" : {"order" : "asc"}}` throws error : 

> `Uncaught Error: Firebase.push failed: first argument  contains an invalid key (vendor.name) in property 'search.request.body.sort.0'.  Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"`

       
I want to be able to tell the elastic search through firebase request that use the nested object field for sorting 
What is the solution to this problem?

**Comment by mike623** [comment]
how do you solve?

**Comment by umarhussain15** [comment]
Well I looked in to the [source code](https://github.com/firebase/flashlight/blob/master/lib/SearchQueue.js#L96) of SearchQueue.js and realized that, we don't necessarily need to set the value of `body` as a simple json like we do in firebase. Instead you first create the JSON for the body value and then stringify the json. Append the output string as value for body.
Flashlight allow this string appending to allow elasticsearch syntax even using firebase.
