### ISSUE TITLE
Indexes not being deleted

### ISSUE THREAD

**Issue by codingwithoutcomments** [firebase/flashlight#22]
After I delete an item from firebase, the index is not being removed from my elastic search server.  The logs however, say the item is being deleted.  But then, when i do another search, the item is still there.

Here is the "deleted" messaged
```
Oct 02 16:33:25 bookreadings-search app/worker.1:  deleted firebase/reading/-JYCgDAf6Fgdbp3Focga 
```

But then, a few minutes after, the index appears in a search result.  (Note the same _ids)
```
Oct 02 16:37:23 bookreadings-search app/worker.1:  search result {"took":1,"timed_out":false,"_shards":{"total":1,"successful":1,"failed":0},"hits":{"total":1,"max_score":1.1399126,"hits":[{"_index":"firebase","_type":"reading","_id":"-JYCgDAf6Fgdbp3Focga","_score":0.06655927,"_source":{"title":"This will be the most played.","tags":["Most Played"],"created":1412200194853}}]}} 
```

**Comment by katowulf** [comment]
Going to close this in favor of a fixit issue.
