### ISSUE TITLE
Just did a fresh install of flashlight

### ISSUE THREAD

**Issue by kyoukhana** [firebase/flashlight#24]
I just did a fresh install of flashligiht but I am getting the following error not sure why

failed to index firebase/userssearch/-JbNpxICq4RijCKHSKhX: Error: getaddrinfo ENOTFOUND

**Comment by katowulf** [comment]
I'm going to assume you're not still working on this. If you made any progress, I'd love to hear the cause.

It sounds like it couldn't find ElasticSearch; probably a bad URL?
