### ISSUE TITLE
It return only no more than 10 results in the Hits array.

### ISSUE THREAD

**Issue by Alphazella** [firebase/flashlight#29]
even if the total of results is more. How can we have more results?

**Comment by mpeterss** [comment]
This is the default value for elasticsearch:

    http://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html

You could for example change the queryObj in SearchQueue.js to another size.

queryObj : { "from" : 0, "size" : 50 , "query": queryObj };

**Comment by katowulf** [comment]
@mpeterss thanks for the find! Think I'll add that morsel to the readme for clarity.

**Comment by idanb11** [comment]
Hi @mpeterss ,
Can you please explain how to use the "from" and "size" in the following object:

```
{
  index: 'firebase',
  type : 'node',      
  query: {
    query_string: {
      query: "hired"
     }
   }
}
```
Thanks.

**Comment by mpeterss** [comment]
{
  index: 'firebase',
  type : 'node',
  from :0,
  size : 50, 
  query: {
    query_string: {
      query: "hired"
     }
   }
}

**Comment by idanb11** [comment]
Hi @mpeterss , 
The query you wrote is not the correct one but I figured it out myself.
The correct way to use "from" and "size" is so:

```
{
	index : 'firebase',
	type : 'node',
	options : {
		from : (page - 1) * cutoff,
		size : cutoff
	},
	query : {
		query_string : {
			query : "*"
		}
	}
}
```

**Comment by afaucogney** [comment]
@idanb11 Thanks for sharing. Did you had to update the security rules ?

**Comment by idanb11** [comment]
no need to update the security rules.

**Comment by afaucogney** [comment]
@idanb11 here are the security rules provided in the example:

         "request": {
            "$recid": {
               // I can only read records assigned to me
               ".read": "auth.id === data.child('id').val() || auth.uid === data.child('id').val()",
               // I can only write new records that don't exist yet
               ".write": "!data.exists() && (newData.child('id').val() === auth.id || newData.child('id').val() === auth.uid)",
               ".validate": "newData.hasChildren(['query', 'index', 'type'])",
               "index": {
                  // accepts arrays or strings
                  ".validate": "(newData.isString() && newData.val().length < 1000) || newData.hasChildren()",
                  "$child": {
                     ".validate": "newData.isString() && newData.val().length < 1000"
                  }
               },
               "type": {
                  // accepts arrays or strings
                  ".validate": "(newData.isString() && newData.val().length < 1000) || newData.hasChildren()",
                  "$child": {
                     ".validate": "newData.isString() && newData.val().length < 1000"
                  }
               },
               "query": {
                  // structure of the query object is pretty open-ended
                  ".validate": "newData.isString() || newData.hasChildren()"
               },
               "$other": {
                  ".validate": false
               }
            }
         },


This can not work ? isn't it ?

**Comment by afaucogney** [comment]
@idanb11 or @mpeterss  or @katowulf I'm still facing to no hits when I use the query options in my search request.

For information, thanks to ES/bonsai support, I succeed making the Bonsai interactive console running:

![capture d écran 2016-05-09 a 12 06 39](https://cloud.githubusercontent.com/assets/6554201/15109993/974b7490-15de-11e6-9696-b4eed6ec02a0.png)

- Select POST request
- Define your url as `index/type/_search`and then put query inside {}

@katowulf adding this to the documentation would be helpful for at lease ES novice.

I have to updated the security rules for both possible ways:

      "search": {
         "request": {
            "$recid": {
               // I can only read records assigned to me
               ".read": "auth.id === data.child('id').val() || auth.uid === data.child('id').val()",
               // I can only write new records that don't exist yet
               ".write": "!data.exists() && (newData.child('id').val() === auth.id || newData.child('id').val() === auth.uid)",
               ".validate": "newData.hasChildren(['query', 'index', 'type'])",
               "index": {
                  // accepts arrays or strings
                  ".validate": "(newData.isString() && newData.val().length < 1000) || newData.hasChildren()",
                  "$child": {
                     ".validate": "newData.isString() && newData.val().length < 1000"
                  }
               },
               "type": {
                  // accepts arrays or strings
                  ".validate": "(newData.isString() && newData.val().length < 1000) || newData.hasChildren()",
                  "$child": {
                     ".validate": "newData.isString() && newData.val().length < 1000"
                  }
               },
               "query": {
                  // structure of the query object is pretty open-ended
                  ".validate": "newData.isString() || newData.hasChildren()"
               },
               "options": {
                  // structure of the query options is pretty open-ended
                  ".validate": "newData.isString() || newData.hasChildren()"
               },
               "from": {
                  // structure of the query options is pretty open-ended
                  ".validate": "newData.isNumber()"
               },
               "size": {
                  // structure of the query options is pretty open-ended
                  ".validate": "newData.isNumber()"
               },
               "$other": {
                  ".validate": false
               }
            }
         },

But it still doesn't work. The response own no hits `request_id:{total:0}` Help would be grateful !

**Comment by katowulf** [comment]
Updated count in the readme and docs. @afaucogney you've hijacked another discussion. Please start your own thread.
