### ISSUE TITLE
Question: Any docs on filter function for the paths?

### ISSUE THREAD

**Issue by DasHutch** [firebase/flashlight#36]
Just trying to figure out how to get the filter working... looking for some insight. As it doesn't seem to be working currently...

`config.js`
```
exports.paths = [
   {
      path:  "products",
      index: "firebase",
      type:  "product",
      fields: ['brands', 'name', 'categories'],
      filter: function(data) {
         return data.live != false || data.searchable != false;
      }
   }
];
```

Still getting all products that match the query string
Any guidance? Articles? etc? having some trouble finding anything...

**Comment by idanb11** [comment]
:+1:

**Comment by afaucogney** [comment]
👍

**Comment by katowulf** [comment]
Please provide a repro if you're having issues. Happy to look into it.

**Comment by DasHutch** [comment]
This was eight months ago, got no response.
I'll close this as I've moved on from this tech

Never got it working correctly and this was a bit less of a bug and more of a request for information since the docs (at the time) were lacking.

Anyway gl to anyone using this, I can't provide anymore help or repro
