### ISSUE TITLE
When listening for new response, the .on('value' callback is called twice

### ISSUE THREAD

**Issue by idanb11** [firebase/flashlight#37]
```
searchRef.child('response/' + key).on('value', function(resSnapshot){
        console.log(resSnapshot.val());
      });
```
the callback executes twice, 
first time with this error - `{error: "IndexMissingException[[firebase] missing]", total: 0}`
second time with the actual data - `{hits: Array[10], max_score: 1, total: 319}`

Just ignore it when i get the error?

when I run this: `curl -X POST http://localhost:9200/firebase/` 
I get: `{"error":"IndexAlreadyExistsException[[firebase] already exists]","status":400}`

Thanks,
Idanb11

**Comment by katowulf** [comment]
Please resubmit this with a failing test or minimal repro and we'll have a look.
