### ISSUE TITLE
Getting different results from elastic search for - on.('value'

### ISSUE THREAD

**Issue by idanb11** [firebase/flashlight#48]
```
null
Object {hits: Array[250], max_score: 1, total: 2053}
Object {hits: Array[250], max_score: 1, total: 1610}
```

How can I know which results is the correct one?

**Comment by katowulf** [comment]
I have no idea what this means: What we're comparing here? What is the origin of those three lines? What data is at those paths. Could you add just a bit more detail?

**Comment by idanb11** [comment]
OK,
You are right, there is not enough info.

I use the following code:

```
searchRef.child('response/' + newSearchKey).on('value', successGetUsersHandler, function(error) {
          console.error("Error:", error);
          updateSpinnerLayout(false);
          vm.gridviewLoading = false;
        });
```
And since on 'value' call the callback anytime the data is changed, the successGetUsersHandler function is executed 3 times.
Once with the value of null (empty)
Once with the correct data
and once again with only a subset of the data received in the previous call.

The way i worked around this problem is to ignore the null.
use the data from the 2nd call and immediately call off 'value' to stop listening for data changes.

Do you have any clue why is it happening?
Thanks...

**Comment by katowulf** [comment]
Thanks for the explanation. Much clearer. What you have here is fairly similar to [the example.js code](https://github.com/firebase/flashlight/blob/master/example/example.js#L33). However, note lines 37 and 38, where we remove the listener as soon as we receive a non-null value and then remove the data.

Not sure why you would receive multiple events with non-null data--somebody has to be changing it more  than once (perhaps you're editing two separate paths in the same data or using update()/PATCH). But the example.js approach should work either way.

**Comment by idanb11** [comment]
OK, Thanks @katowulf .
