### ISSUE TITLE
High volume traffic spikes Heroku worker memory results in slow performance

### ISSUE THREAD

**Issue by liltimtim** [firebase/flashlight#51]
<img width="856" alt="screen shot 2015-08-28 at 8 16 43 am" src="https://cloud.githubusercontent.com/assets/4106065/9546027/246110f6-4d5d-11e5-94b1-895ab8e2e2c4.png">
Hello,

We currently use the flashlight app (out of the box) in production.  I haven't made any modifications to your code in our Heroku environment.  

I've tried several tiers of Heroku to attempt to solve this.  Currently, we are at the largest Heroku worker tier Performance - L I believe is the name (the 500 a month one).  The instance runs fine except when we see hi volume of updates on firebase and when we have many thousands of clients updating firebase at once.  

I've attached an image to show the usage statistics and to show the out of memory errors we are getting.  My theory is that the .on function queues up changes to be made to elastic (the updating of indexes).  This queue fills up so quickly that the worker is unable to process them and begins to have a backlog of changes to be made thus filling up available memory.  As the worker struggles to complete tasks it falls more and more behind and eventually slows to a crawl while catching up.  

My question: is there a way to resolve this issue by distributing the work evenly among many workers? I've tried spinning up several worker instances but they all seem to work on indexing the same path together.  It is only when there is high volume traffic where I see one worker doing another process different from other workers.  I am using Heroku logs --tail to get this data and make this assumption.  

I've also tried replacing the unsupported elasticsearchclient with the official client but the Heroku instances just crash or spit out errors I haven't seen before.  I have also upgraded elastic.js to version 1.2.0 and I still see these issues. Luckily the server doesn't exactly crash when under stress it just crawls very slowly until it's able to catch up regardless of how many resources I throw at it. 

Thank you,
TB

**Comment by zzimbler** [comment]
Seeing the exact same issue @jcbeaury

**Comment by katowulf** [comment]
You'll need to adapt the code to work with multiple workers. See firebase-queue for a great scalable, multi-worker queue strategy. That's beyond the scope of what we can support for this repo at the moment, but we'd love any and all pull requests to improve scaling and to support multiple workers.

> I've also tried replacing the unsupported elasticsearchclient with the official client but the Heroku instances just crash or spit out errors I haven't seen before.

I can help with "just crash and spit out errors"; you'll need to be more specific. I would consider upgrading to the official client an important step of improving scale, as this is necessary to support [batch processing](https://github.com/firebase/flashlight/issues/34).
