### ISSUE TITLE
How to make flashlight work on the Google Cloud Platform?

### ISSUE THREAD

**Issue by pluminik** [firebase/flashlight#53]
So, I uploaded my website to the web [as a static site via Cloud Storage](https://cloud.google.com/storage/docs/website-configuration), then I used the [click-to-deploy GCP feature](https://cloud.google.com/solutions/elasticsearch/click-to-deploy), but I don't know how to connect the two things.

Even an informal, quick set of instructions written here below, would help a great deal!
Thanks!

**Comment by katowulf** [comment]
Flashlight is a simple server-side node.js script. Following the process for deploying a node JS script should be all you need here. https://cloud.google.com/nodejs/
