### ISSUE TITLE
Does flashlight scale horizontally?

### ISSUE THREAD

**Issue by dotboris** [firebase/flashlight#56]
I am working on a firebase app. In this app, I use elasticsearch and flashlight for searching through my content. Currently our customer base is rather small. Because of this we are hosting flashlight on a single server on AWS.

We are planning to get a quite significant growth in our customer base. With this new growth, we'll need to scale flashlight. We hope to be able to scale it horizontally by running multiple instances of flashlight and a elasticsearch cluster.

Is this possible?

From what I understand, the searching should not be a problem but the indexing might be. My understanding is that flashlight indexes content every time there's a change in firebase. If we have multiple instances of flashlight, when a change is made that requires indexing all of the servers will be notified and they'll all try to index.

If this is the case, we're never really scaling horizontally for indexing and we might end up with some inconsistencies in our index.

**Comment by katowulf** [comment]
The tool as it exists would not allow you to scale in this manner. Depending on what sort of data structures you need to index, you could probably set up multiple servers to monitor different paths and index them.

One inefficiency here is that the current indexing will re-index the entire path if the server is restarted and that we haven't taken advantage of batching, which is [fixed here](https://github.com/firebase/flashlight/pull/54), we just need to test the patch and approve.

**Comment by robotnoises** [comment]
It's been a while, but I don't remember implementing any batching in https://github.com/firebase/flashlight/pull/54 ... Perhaps it was https://github.com/firebase/flashlight/pull/25 ?

**Comment by adelespinasse** [comment]
Seems to me it shouldn't be too hard to adapt Flashlight to scale. You'd just need to add a field to each indexed structure, which would get a random number assigned by the client when a new record is created. You'd have multiple Flashlight servers each restricting its query based on that field. You could do something similar for searches.

(This is assuming Elastic Search can handle arbitrary volume of new indexing data arriving from multiple Flashlight servers... I have no idea about that.)

The fact that "the current indexing will re-index the entire path if the server is restarted" is sort of disturbing, although I guess it's better to re-index than to risk dropping data. It wasn't clear from the comment by @katowulf above whether the referenced PR fixes that issue, or just the lack of batching.

**Comment by katowulf** [comment]
It only addresses batching afaik. Closing this question as resolved. If someone wants to start a spec and PR for adding some horizontal scale, I'll welcome this, but won't be tackling it.
