### ISSUE TITLE
Mapping options (multifields, etc)

### ISSUE THREAD

**Issue by andrewatwood** [firebase/flashlight#57]
Any support for custom mapping? Need to work with some multifields and can't see where to pass these options to the elasticsearchclient.

**Comment by katowulf** [comment]
I don't know what multifields are or custom mappings, sorry. But you can put whatever you want into `queryObj` as this is directly passed into the ES API.

**Comment by andrewatwood** [comment]
Good to know. 

Turns out the issue I was having was solved by setting custom mapping on your index before ever running Flashlight. As long as you have those options set before the first document is indexed, anything added will follow those rules.

**Comment by kidequinox** [comment]
@andrewatwood can you provide details in how you setup custom mapping prior to running firebase ?

**Comment by andrewatwood** [comment]
@kidequinox yeah just use curl to PUT the JSON of the mapping (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html) before running Flashlight and you'll be good to go. Will have to delete and re-map the index whenever you need to change it but if it's right from the beginning it'll work great.

**Comment by kidequinox** [comment]
@andrewatwood Thanks!!!!
