### ISSUE TITLE
Example for providing dynamic paths in the config.

### ISSUE THREAD

**Issue by sivaramsi** [firebase/flashlight#58]
Could you guys provide example for indexing dynamic path using flashlight.

**Comment by katowulf** [comment]
PRs welcome!

**Comment by weislanes** [comment]
The documentation provided simply isn't enough for somebody wanting to add useful search to their Firebase app - the high number of issues reflects that. Better docs would be appreciated.

**Comment by katowulf** [comment]
PRs still welcome, as well as specific topics you'd like to see covered. Flashlight is a relatively simple tool and most of the topics you'll need to understand are specific to ElasticSearch, so it's hard to decide what else we need to have here. Happy to take the feedback.

Also, your expectations for a high number of issues seem a bit skewed. For comparison, here's a project with a [high number of issues](https://github.com/angular/angular/issues).

**Comment by weislanes** [comment]
:) OK, that link was both enlightening and terrifying. 

After trying to get this working with Bonsai I ended up switching to Algolia, and it just works. I pay for that advantage of course. My gripe is that like many I come here from the official Firebase website while searching for some basic search functionality and have to wade through issues, the example code and elasticsearch's API to make any progress.

No doubt flashlight is magic when it works, and kudos for the achievement, I only wish we had something embedded with Firebase proper.

**Comment by katowulf** [comment]
That's great feedback that I'll take back to the team. I'd love to see some better search integrations out of the box as well!

**Comment by katowulf** [comment]
Dynamic path monitoring added and documented.
