### ISSUE TITLE
Question regarding setup with new Firebase

### ISSUE THREAD

**Issue by hellojeffy** [firebase/flashlight#64]
Hi Firebase team, what is the FB_NAME and FB_TOKEN in the following setup command for Heroku/Bonsai?

`heroku config:set FB_NAME=<instance> FB_TOKEN="<token>"`

Is FB_NAME Firebase app name?
If so, is it with the letters/numbers following it due to the new Firebase setup where it's no longer app_name.firebaseio.com but app_name-abc123.firebaseio.com?

and what is FB_TOKEN? (is it a key or something in my google plist I download?)

Thanks in advance!

**Comment by katowulf** [comment]
See #62
