### ISSUE TITLE
geolocation queries

### ISSUE THREAD

**Issue by aTylerRice** [firebase/flashlight#76]
I have my fields setup like

```
{
      "location" : {
            "lat" : 40.12,
            "lon" : -71.34
        }
}
```

I added the location field as one to watch but does this work to do geo distance queries like on here https://www.elastic.co/guide/en/elasticsearch/reference/2.3/query-dsl-geo-distance-query.html

**Comment by irfaan** [comment]
Forgive me if I'm misunderstanding here, but I think you're after this: https://github.com/firebase/geofire-js/blob/master/examples/README.md

**Comment by katowulf** [comment]
Geo is outside the scope of this lib.

**Comment by c0d3blooded** [comment]
If "the body object can be any valid ElasticSearch DSL structure" according the Flashlight docs, wouldn't that include ElasticSearch's built in geo distance queries?

**Comment by leesolway** [comment]
Sorry to be a pain, but it would be useful to understand or see an example of how to define custom data types, such as lat/long geo_point.

Is it actually possible?

**Comment by katowulf** [comment]
Is that something other than a string or number? What exactly makes those a custom data type?
