### ISSUE TITLE
Flashlight not returning data on heroku

### ISSUE THREAD

**Issue by Shaiwal** [firebase/flashlight#80]
Hi, When I try running the flashlight along with elasticsearch on my local connecting to remote firebase it works fine but somehow when I configured it following the exact steps it is not returning any data. Can you please help?
{
took: 1,
timed_out: false,
_shards: {
total: 1,
successful: 1,
failed: 0
},
hits: {
total: 0,
max_score: null,
hits: [ ]
}
}

**Comment by katowulf** [comment]
There are no results for the search you're attempting. Looks like everything is working fine. Obviously, would need a minimal repro and sample data demonstrating an actual problem before I could be much help here.
