### ISSUE TITLE
ES does not return any value

### ISSUE THREAD

**Issue by banaszeknorbert** [firebase/flashlight#82]
Hi guys,
I'm trying to hook up my database to ElasticSearch. I did all things and it's partially running.
Why partially? When I call 'http://localhost:9200/firebase/user/_search' in postman with query 
'{"query":{"bool":{"must":[{"match":{"visibleName":"skye"}},{"match":{"userRole":10}}]}}}' it's returning something like this:
`{
  "took": 3,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 1,
    "max_score": 5.436413,
    "hits": [
      {
        "_index": "firebase",
        "_type": "user",
        "_id": "2nzz9Dd0kcdgxYOsou2lqNPD1uJ2",
        "_score": 5.436413,
        "_source": {
            .....
          "userRole": 10,
          "visibleName": "skye"
        }
      }
    ]
  }`
This user I was looking for. The problem comes when I try to execute a query from my android application. It's (query) finally looks like:
`"-KSCCogBkV2BpjGeJ-jO" : {
        "index" : "firebase",
        "query" : {
          "query" : {
            "bool" : {
              "must" : [ {
                "match" : {
                  "visibleName" : "skye"
                }
              }, {
                "match" : {
                  "userRole" : 10
                }
              } ]
            }
          }
        },
        "type" : "User"
      },`
After that, my datasnapshot is DataSnapshot { key = -KSCoGGRuEYgk4Y7lhCr, value = {.priority=1.474479330934E12, total=0} }.

Am I doing something wrong?

**Comment by katowulf** [comment]
Can you create a minimal repro with sample data and version info?

**Comment by banaszeknorbert** [comment]
Could you write in more detail, what do you expect?

**Comment by katowulf** [comment]
Queries have been heavily revised and improved. I'm going to assume this is solved by the latest batch of changes. If not, submit a working repro of the problem I can run locally to verify.
