### ISSUE TITLE
Firebase Flashlight (ElasticSearch) filtering, sorting, pagination

### ISSUE THREAD

**Issue by manishkpr** [firebase/flashlight#83]
I am using [Flashlight Firebase](https://github.com/firebase/flashlight) plugin

I am using this [example](https://github.com/firebase/flashlight/tree/master/example) and it's working fine

In the example you can see [example.js](https://github.com/firebase/flashlight/blob/master/example/example.js) file have method for query as below

    // display search results
     function doSearch(index, type, query) {

        var ref = database.ref().child(PATH);
        var key = ref.child('request').push( { index: index, type: type, query: query }  ).key;
         ref.child('response/'+key).on('value', showResults);

     }
above function returning me the results when I pass values like following JSON

    { index: index, type: type, query: query }
It returning me nothing when i am trying to pass values like following JSON

    { index: index, type: type, query: { "from" : 1, "size" : 5 , "query": query }
but the following ElasticSearch API returning me the result

    http://localhost:9200/firebase/user/_search?q=*mani*&pretty&size=5&from=1

and How do i filtering the query using Flashlight like following

      {
         "query": {
        "filtered": {
            "query": {
                "query_string": {
                    "query": "drama"
                }
            },
           "filter": {
                //Filter to apply to the query
            }
         }
       }
    }

I am using [example security rules](https://github.com/firebase/flashlight/blob/master/example/seed/security_rules.json)

  
Please let me know how to perform complex queries and filtering with Flashlight

**Comment by manishkpr** [comment]
Finally I did it myself

here is the solution

You need to update [SearchQueue.js](https://github.com/firebase/flashlight/blob/master/lib/SearchQueue.js)

     _process: function (snap) {
      var dat = snap.val();
      var key = snap.key;

    if (this._assertValidSearch(key, dat)) {

      // get your query string

    var q = dat.query.query;
    console.log('search', "test", JSON.stringify(dat, null, 2));
    // build your ES query
    //var q1 = {"query":{"match":{"_all":q}}};
        // Perform (a very simple) ElasticSearch query
        this.esc.search({
            index: dat.index,
            type: dat.type,
            // add options 
            from : dat.query.from,
            size : dat.query.size,
            // add ES Query
            //body : q1
            q:dat.query.query
        }, function (error, response) {
            if (error) {
                this._reply(key, {error: error, total: 0});
            } else {
                this._reply(key, response);
            }
        }.bind(this));
    }
    }
and update [Example.js](https://github.com/firebase/flashlight/blob/master/example/example.js)

       // display search results
        function doSearch(index, type, query) {
             var ref = database.ref().child(PATH);
             var jsonOBJ = { 
                index: index, 
                type: type, 
                query: { size:1, from:0, query},
             };
           var key = ref.child('request').push(jsonOBJ).key;
           console.log('search', key, JSON.stringify(jsonOBJ, null, 2));
          ref.child('response/'+key).on('value', showResults);
     }

**Comment by sauravexodus** [comment]
@manishkpr How did you do sorting?
