### ISSUE TITLE
Use of Parser in Export Path

### ISSUE THREAD

**Issue by mattmarquard** [firebase/flashlight#88]
Do you have an example of using the "parser" key in export paths?

For one of the paths I'm using, I want to create a new field for a particular doc_type from 2 of the existing fields. Specifically, I get a lat and lon field from Firebase which I want to get indexed as a 'location' field for geo-point searching. I was hoping I could do this with "parser".

**Comment by katowulf** [comment]
Hi Matt, great question. It's literally just a function that takes the current JSON value of the Firebase record and returns a new JSON value, declared [here](https://github.com/firebase/flashlight/blob/master/lib/PathMonitor.js#L13) and used [here](https://github.com/firebase/flashlight/blob/master/lib/PathMonitor.js#L34).

```
let config = {
   // other config props
   parser:  function(dataRecord) {
        return {
            foo: dataRecord.foo,
            date: reformatDate(dataRecord.date)
        }
   }
};

// take a timestamp and convert it to an ISO formatted date
function reformatDate( timestamp ) {
    return new Date(timestamp).toISOString();
}
```

**Comment by mattmarquard** [comment]
Thanks for the response, katowulf. That sorted it out for me.
