### ISSUE TITLE
Flashlight not returning values (ES does when bypassing flashligt)

### ISSUE THREAD

**Issue by florianbepunkt** [firebase/flashlight#89]
I cloned the repo, setup my data and paths. Flashlight pushes all data successfully to ES for indexing, but I have problems with setting up queries in flashlight…

When using Sense I can curl ES databse directly. For example this basic query returns some hits

```
POST _search
{
   "query" : {
        "constant_score" : { 
        "filter" : {
          "bool" : {
            "must": [
               {
                "terms": {
                    "gender": ["female"]
                }
              }
            ]
          }
        }
      }
    }
}
```

But what would I need to pass to function doSearch(index, type, query) method?
When passing the following object as query argument I don't get any results back.

```

{
        "constant_score" : { 
        "filter" : {
          "bool" : {
            "must": [
               {
                "terms": {
                    "gender": ["female"]
                }
              }
            ]
          }
        }
      }
    }

```

An example of how to pass a ES query json object to doSearch() would be handy…

**Comment by katowulf** [comment]
Hi Florian, I just committed a couple improvements to the querying example, but I'm still not sure it's working up to what you want here. Could you create a query example that uses the [existing data](https://flashlight.firebaseio.com/.json?print=pretty) we could use as a test? If you'll set up the ES portion, I'll be happy to fiddle and see what we need to get it running.

**Comment by florianbepunkt** [comment]
Hi Kato, figured it out after some digging into the code…  in your example you passed  a simple query string to elasticsearch client. In the elasticsearch docs they use this as the most simple example but for literally everything else they specify a body that contains query in their DSL json syntax. so maybe it would be more inclusive to use the seconds approach since you can do query string searches with a request body as you can every other search ES allows, but not the other way around.

`this.esc.search({
    index: 'roomary_users',
    type: 'users',
	body: {
		size: 3,
		from: initialQuery ? 0 : 3,
		query: {
			'query_string': {
                            'query': 'this AND that OR thus'
                        }
		}
	}
});`

Unrelated to my issue: I adapting flashlight a lot to my specific needs now, but if it is of any intereset I can submit a pr for more general features like processing documents in batches on server start or storing indexing state of elements in watched parts, so that we don't need to reindex the whole path on flashlight restart.

**Comment by katowulf** [comment]
Right, what I'm looking for here is an interesting query that matches the existing data we can use as a test. Right now, the server will accept an object for the `query` parameter, which becomes the `body` attribute in the query to ES, but that is the part that I suspect isn't working as expected.

Since ES queries aren't my specialty, if you can construct something that creates a reasonably decent test unit to run against our example data, it will speed up working out the bugs.

**Comment by florianbepunkt** [comment]
Just had a quick look… can't tell for sure since I built my search/result process based on firebase-queue for scalability. But I guess the problem is in  flashlight/lib/SearchQueue.js, line 27:

if( typeof dat.query === 'string' ) { searchProps.q = dat.query ; }
else { dat.body = searchProps.query ; }

this would end up in a call to elasticsearch js client like when I have an object for query parameter

```
this.esc.search({
    index: 'myindex',
    type: 'mytype',
		query: {
			// your DSL query here
		}
});
```

when in fact it should be…

```
this.esc.search({
    index: 'myindex',
    type: 'mytype',
	body: {
		query: {
			// your DSL query here
		}
	}
});
```

but like I said… just a wild guess.

**Comment by katowulf** [comment]
No, the `query` parameter on the client gets processed and converted to `q` if it's a string or `body` if it's an object [here](https://github.com/firebase/flashlight/blob/master/lib/SearchQueue.js#L28). See [comments in the demo script](https://github.com/firebase/flashlight/blob/master/example/example.js#L48).
