### ISSUE TITLE
Not all data is indexed

### ISSUE THREAD

**Issue by tallminator** [firebase/flashlight#92]
Every time I delete the Elastic search index using `curl -XDELETE 'http://localhost:9200/firebase/'` and start the Flashlight app using `node app.js` different number of documents are indexed. For example, if the corresponding Firebase location has 10 nodes, the index only has 7 (I find this number using `curl -XGET 'http://localhost:9200/firebase/_count'`).

I'm having to go through this above routine 3 or 4 times before all documents are indexed. New data is getting indexed in real time. Just that whenever I do a hard reindex like above, it takes 3 or 4 tries to get the index on par with the Firebase location.

**Comment by katowulf** [comment]
Try turning on debug logging and see what is happening on the Firebase side: `firebase.database().enableLogging(true);`

Similarly, enable logging from the ES client to see what's happening over HTTP: `var client = new elasticsearch.Client({ log: 'trace' });`

(or if that's too verbose, you can try something like `var client = new elasticsearch.Client({ log: ['error', 'warning', 'trace'] });`

**Comment by mbifulco** [comment]
Any chance this is related to #74?

**Comment by katowulf** [comment]
Not at such a small volume, no. Batching comes into play with the number of index requests exceeds what ES will accept.

**Comment by mbifulco** [comment]
Fair point.

**Comment by katowulf** [comment]
No ideas here and no response to my request for more data. Closing for now. We can reopen if details are added.
