### ISSUE TITLE
[question] type of children / query children

### ISSUE THREAD

**Issue by hervesoulie** [firebase/flashlight#93]
Hi !
I have a db structure which looks like this 

> root
>  -> projects
>  ---> project objects
>  -> project_files
>  ---> project_uid
>  ------> project_files objects

I structured it like this as I want each project to be independent (won't and will never cross data between them)

The exports.path contains this object :
```
  {
      path  : "project_files",
      index : "firebase",
      type  : "project_files"
   }
```
I need to query the project_files but, even if I know the project_uid, because the nodes under it are not typed, I can't. 

So my questions are : 
Can I configure the exports.path in order to type the children under the project_uid node ? If yes, how ? If no, would you suggest me something in order to achieve this ?

Thanks !

**Comment by katowulf** [comment]
Looks like [this discussion](https://github.com/firebase/flashlight/issues/84#issuecomment-250212991) is similar.

**Comment by hervesoulie** [comment]
It is indeed ! Thank you @katowulf  !
