### ISSUE TITLE
using firebase-queue for monitoring and indexing paths

### ISSUE THREAD

**Issue by florianbepunkt** [firebase/flashlight#94]
This is half-way enhancement sugestion / half-way question / half-way proposal I guess.  I was thinking of using firebase-queue for the path monitor…. The current solution IMO has the following limitations:

- flashlight renindexes the whole path on restart
- flashlight does not scale well

Kato, can you please comment on whether it would be a good idea to use firebase-queue as a path monitor? Say for example I have a /user path I want to monitor and index to ES. I would setup a firebase queue with /user as my queue path and a custom spec like this

```
index_spec
-- error_state: "error"
--  finished_state: "indexed"
-- in_progress_state: "indexing"
-- retries: 3
-- start_state: "index"
-- timeout: 300000
```
 
I'm unsure how this would scale however. Let's image /users path would have thousand of entries (all with finished state "indexed"). Would this slow down the firebase-queue? I guess it shouldn't since it only cares about the nodes with a state value of "index", but I'm not sure.

Thanks,
Florian

**Comment by katowulf** [comment]
Added some additional options in 0.2.0 that can help avoid indexing the whole path on restart. Using firebase-queue behind the scenes is very interesting and possible a great option, but probably complex. Will probably revisit this when Firebase integrates with Google Cloud Functions and find a more scalable and simple answer.
